// config/presetPizzas.js

const PRESET_PIZZAS = [
  {
    id: 1,
    name: 'Cowabunga Classic',
    description: 'Pepperoni, mozzarella, red sauce.',
    price: 14.99,
    isAvailable: true,
    category: 'pizza',
    imageUrl: '/images/pizza-classic.png',
  },
  {
    id: 2,
    name: 'Turtle Supreme',
    description: 'Sausage, pepperoni, peppers, onions, olives.',
    price: 16.99,
    isAvailable: true,
    category: 'pizza',
    imageUrl: '/images/turtle-pizza.png',
  },
  {
    id: 3,
    name: 'Veggie Dojo',
    description: 'Mushrooms, peppers, onions, olives, spinach.',
    price: 15.99,
    isAvailable: true,
    category: 'pizza',
    imageUrl: '/images/pizza-veggie.png',
  },

  // Sides
  {
    id: 4,
    name: 'Garlic Knots',
    description: 'Fresh-baked knots brushed with garlic butter and herbs.',
    price: 5.99,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },
  {
    id: 5,
    name: 'Breadsticks',
    description: 'Soft breadsticks with garlic butter and parmesan.',
    price: 5.49,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },
  {
    id: 6,
    name: 'Buffalo Wings (6pc)',
    description: 'Crispy wings tossed in classic buffalo sauce, served with ranch.',
    price: 9.99,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },
  {
    id: 7,
    name: 'BBQ Wings (6pc)',
    description: 'Sweet and smoky BBQ wings, perfect for sharing.',
    price: 9.99,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },
  {
    id: 8,
    name: 'Crispy Fries',
    description: 'Golden, crispy fries seasoned with sea salt.',
    price: 4.49,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },
  {
    id: 9,
    name: 'Loaded Fries',
    description: 'Fries loaded with cheese sauce and bacon bits.',
    price: 6.99,
    isAvailable: true,
    category: 'side',
    imageUrl: '',
  },

  // Desserts
  {
    id: 10,
    name: 'Fudge Brownie',
    description: 'Rich, chewy chocolate brownie with a crackly top.',
    price: 3.49,
    isAvailable: true,
    category: 'dessert',
    imageUrl: '',
  },
  {
    id: 11,
    name: 'Chocolate Chip Cookie',
    description: 'Big bakery-style cookie packed with chocolate chips.',
    price: 2.49,
    isAvailable: true,
    category: 'dessert',
    imageUrl: '',
  },
  {
    id: 12,
    name: 'Cinnamon Sugar Twists',
    description: 'Warm dough twists tossed in cinnamon sugar with icing drizzle.',
    price: 5.99,
    isAvailable: true,
    category: 'dessert',
    imageUrl: '',
  },
  {
    id: 13,
    name: 'Cheesecake Bites',
    description: 'Bite-sized vanilla cheesecake pieces with graham cracker crust.',
    price: 6.49,
    isAvailable: true,
    category: 'dessert',
    imageUrl: '',
  },

  // Drinks
  {
    id: 14,
    name: 'Classic Soda (Can)',
    description: '12oz can of ice-cold soda.',
    price: 1.99,
    isAvailable: true,
    category: 'drink',
    imageUrl: '',
  },
  {
    id: 15,
    name: 'Assorted Sodas (Can)',
    description: 'Selection of cola, lemon-lime, and orange sodas.',
    price: 2.29,
    isAvailable: true,
    category: 'drink',
    imageUrl: '',
  },
  {
    id: 16,
    name: 'Bottled Water',
    description: 'Chilled bottled water.',
    price: 1.49,
    isAvailable: true,
    category: 'drink',
    imageUrl: '',
  },
  {
    id: 17,
    name: 'Fountain Drink',
    description: 'Soft drink served over ice in a fountain cup.',
    price: 2.49,
    isAvailable: true,
    category: 'drink',
    imageUrl: '',
  },
];

module.exports = PRESET_PIZZAS;
